server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: info,beans
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: system123#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#spring:
#  security:
#    user:
#      name: prashant
#      password: admin
